site_name: Autolab Docs
pages:
    - Autolab:
        - Getting Started: index.md
        - Guide for Instructors: instructors.md
        - Guide for Lab Authors: lab.md
        - Features: features.md
        - API (Beta Feature):
            - Overview: api-overview.md
            - Reference: api-interface.md
    - Tango:
        - Getting Started: tango.md
        - Tango CLI: tango-cli.md 
        - REST API: tango-rest.md
        - VMMS Docs: tango-vmms.md
        - Deploying Tango: tango-deploy.md
    - OneClick Install: one-click.md
theme: null
theme_dir: 'mkdocs-material/material'
repo_name: 'Autolab'
repo_url: 'https://github.com/Autolab/autolab'
extra:
  logo: 'images/logo.svg'
  palette:
     primary: 'red'
     accent: 'blue'
  social:
    - type: 'github'
      link: 'https://github.com/Autolab'
    - type: 'facebook'
      link: 'https://facebook.com/autolabproject'
google_analytics:
  - 'UA-79424729-3'
  - 'auto'
markdown_extensions:
  - admonition
  - codehilite(linenums=true)
strict: true
